### ISSUE TITLE
Take a file as an argument

### ISSUE THREAD

**Issue by Compro-Prasad** [Compro-Prasad/convex-hull#1]
File will contain each point on a separate line, the coordinates separated with spaces. Example,
```
3 4
5 6
8 9
10 2
```
Taking the points as input, list the output in the same format. If no such points are found print `undefined`. In other edge cases like large number of points print `out of bounds`, etc.

**Comment by vishvanath45** [comment]
I can fix this!

**Comment by vishvanath45** [comment]
I am using `double` data type for points which has range from 1.7E +/- 308 (15 digits), and `long long int` for no. of inputs points, which has range from –9,223,372,036,854,775,808 to 9,223,372,036,854,775,807, which covers nearly all the cases which user can give, do we need additional check?

**Comment by Compro-Prasad** [comment]
Check if the points can be easily put in a vector/array
